# Gradle
org.gradle.jvmargs=-Xmx4086m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.tooling.parallel=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true

# Kotlin
kotlin.code.style=official